





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data.Items;
using Sitecore.Globalization;


namespace SimpleAbstractIoC.Web.Models
{

	public partial interface IGlassBase{
		
		[SitecoreItem]
        Item SitecoreItem { get; set; }

		[SitecoreId]
		Guid Id{ get; set; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; set; }

		[SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; set; }

		[SitecoreField("__Sortorder")]
        int Sortorder { get; set; }

		[SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        IEnumerable<Guid> BaseTemplateIds { get; set; }

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        string ContentPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        string DisplayName { get; set; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        string FullPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; set; }

        [SitecoreChildren(InferType = true)]
        IEnumerable<IGlassBase> Children { get; set; }

        [SitecoreParent(InferType = true)]
        IGlassBase Parent { get; set; }
	}
}
namespace SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages
{


 	/// <summary>
	/// IGeneric_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Simple IoC/Pages/Generic Page</para>	
	/// <para>ID: 0407e365-6a97-4871-bbfe-e2e7680c540a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IGeneric_Page : IGlassBase 
	{
						/// <summary>
			/// The Page Content field.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: e9275902-9f46-4aad-abdc-65edc29859f0</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Page_Constants.Page_Content_FieldName, ReadOnly = true)]
						string Page_Content  { get; set; }

			/// <summary>
			/// The Page Content field in RAW format.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: e9275902-9f46-4aad-abdc-65edc29859f0</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Page_Constants.Page_Content_FieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Page_Content_Raw  { get; set; }
		
					
					/// <summary>
			/// The Page Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: aa160f5f-2b26-4449-a1bd-4c39c441a9cb</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Page_Constants.Page_Title_FieldName)]
						string Page_Title  { get; set; }
				}

	public static partial class IGeneric_Page_Constants{

			public const string TemplateIdString = "0407e365-6a97-4871-bbfe-e2e7680c540a";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Page";

					
			public static readonly Guid Page_Content_FieldId = new Guid("e9275902-9f46-4aad-abdc-65edc29859f0");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("aa160f5f-2b26-4449-a1bd-4c39c441a9cb");
			public const string Page_Title_FieldName = "Page Title";
			
			

	}


}
namespace SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages
{


 	/// <summary>
	/// IHome_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Simple IoC/Pages/Home Page</para>	
	/// <para>ID: 8379edde-af5c-4e15-9243-265a1a91d360</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IHome_Page : IGlassBase , global::SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages.IGeneric_Page
	{
		}

	public static partial class IHome_Page_Constants{

			public const string TemplateIdString = "8379edde-af5c-4e15-9243-265a1a91d360";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Home Page";

					
			public static readonly Guid Page_Content_FieldId = new Guid("e9275902-9f46-4aad-abdc-65edc29859f0");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("aa160f5f-2b26-4449-a1bd-4c39c441a9cb");
			public const string Page_Title_FieldName = "Page Title";
			
			

	}


}
namespace SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages
{


 	/// <summary>
	/// ILogin_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Simple IoC/Pages/Login Page</para>	
	/// <para>ID: b32be52c-2671-4896-ae29-739d5229ff09</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILogin_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ILogin_Page : IGlassBase , global::SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages.IGeneric_Page
	{
			
					/// <summary>
			/// The Default Redirect Page field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: fc9479d8-ef0d-482b-b19d-ae7f6b3ebda4</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ILogin_Page_Constants.Default_Redirect_Page_FieldName)]
						Guid Default_Redirect_Page  { get; set; }
					
					/// <summary>
			/// The Email Field Label field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 2596b8f5-5c03-49af-bcac-5d8dc5095d21</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ILogin_Page_Constants.Email_Field_Label_FieldName)]
						string Email_Field_Label  { get; set; }
					
					/// <summary>
			/// The Generic Error Message field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 2e42dff7-6e49-4bfe-b003-006f1cc5e70e</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ILogin_Page_Constants.Generic_Error_Message_FieldName)]
						string Generic_Error_Message  { get; set; }
					
					/// <summary>
			/// The Login Button Label field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 1a0ed4aa-ec2e-4a0d-b623-474d82a7fbe1</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ILogin_Page_Constants.Login_Button_Label_FieldName)]
						string Login_Button_Label  { get; set; }
					
					/// <summary>
			/// The Password Field Label field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: acddc113-63d7-4538-a7af-39942007022f</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ILogin_Page_Constants.Password_Field_Label_FieldName)]
						string Password_Field_Label  { get; set; }
				}

	public static partial class ILogin_Page_Constants{

			public const string TemplateIdString = "b32be52c-2671-4896-ae29-739d5229ff09";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Login Page";

					
			public static readonly Guid Default_Redirect_Page_FieldId = new Guid("fc9479d8-ef0d-482b-b19d-ae7f6b3ebda4");
			public const string Default_Redirect_Page_FieldName = "Default Redirect Page";
			
					
			public static readonly Guid Email_Field_Label_FieldId = new Guid("2596b8f5-5c03-49af-bcac-5d8dc5095d21");
			public const string Email_Field_Label_FieldName = "Email Field Label";
			
					
			public static readonly Guid Generic_Error_Message_FieldId = new Guid("2e42dff7-6e49-4bfe-b003-006f1cc5e70e");
			public const string Generic_Error_Message_FieldName = "Generic Error Message";
			
					
			public static readonly Guid Login_Button_Label_FieldId = new Guid("1a0ed4aa-ec2e-4a0d-b623-474d82a7fbe1");
			public const string Login_Button_Label_FieldName = "Login Button Label";
			
					
			public static readonly Guid Password_Field_Label_FieldId = new Guid("acddc113-63d7-4538-a7af-39942007022f");
			public const string Password_Field_Label_FieldName = "Password Field Label";
			
					
			public static readonly Guid Page_Content_FieldId = new Guid("e9275902-9f46-4aad-abdc-65edc29859f0");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("aa160f5f-2b26-4449-a1bd-4c39c441a9cb");
			public const string Page_Title_FieldName = "Page Title";
			
			

	}


}
namespace SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages
{


 	/// <summary>
	/// IMy_Account_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Simple IoC/Pages/My Account Page</para>	
	/// <para>ID: f1d25524-731c-41c0-9561-8d7121103da4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMy_Account_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IMy_Account_Page : IGlassBase , global::SimpleAbstractIoC.Web.Models.sitecore.templates.Simple_IoC.Pages.IGeneric_Page
	{
			
					/// <summary>
			/// The Welcome Prefix field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 6959f0f9-b114-4537-8501-b91fbdc37792</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IMy_Account_Page_Constants.Welcome_Prefix_FieldName)]
						string Welcome_Prefix  { get; set; }
					
					/// <summary>
			/// The Your Messages Label field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: c4734212-e35b-4d98-b698-a984c7888322</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IMy_Account_Page_Constants.Your_Messages_Label_FieldName)]
						string Your_Messages_Label  { get; set; }
				}

	public static partial class IMy_Account_Page_Constants{

			public const string TemplateIdString = "f1d25524-731c-41c0-9561-8d7121103da4";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "My Account Page";

					
			public static readonly Guid Welcome_Prefix_FieldId = new Guid("6959f0f9-b114-4537-8501-b91fbdc37792");
			public const string Welcome_Prefix_FieldName = "Welcome Prefix";
			
					
			public static readonly Guid Your_Messages_Label_FieldId = new Guid("c4734212-e35b-4d98-b698-a984c7888322");
			public const string Your_Messages_Label_FieldName = "Your Messages Label";
			
					
			public static readonly Guid Page_Content_FieldId = new Guid("e9275902-9f46-4aad-abdc-65edc29859f0");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("aa160f5f-2b26-4449-a1bd-4c39c441a9cb");
			public const string Page_Title_FieldName = "Page Title";
			
			

	}


}
